# -*- python -*-
Import("env")
import glob

#
# Tests
#
import lsst.tests

ignoreList = [ "getBias.py", "getFlat.py", "getRaw.py", "md.py" ]
tests = lsst.tests.Control(env, ignoreList=ignoreList, verbose = True)
tests.run("*.py")
